# Uncomment to define a global platform for your project
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', 'Debug' => :debug, 'Profile' => :release, 'Release' => :release

def parse_xcconfig(file)
  File.foreach(file).each_with_object({}) do |line, memo|
    key_match = line.match(/^\s*(\S+)\s*=\s*(\S+)/)
    next unless key_match
    memo[key_match[1]] = key_match[2]
  end
end

flutter_root = ENV['FLUTTER_ROOT'] || parse_xcconfig(File.join('Flutter', 'Generated.xcconfig'))['FLUTTER_ROOT']
raise "Could not find FLUTTER_ROOT" if flutter_root.nil?

require File.expand_path(File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper'))

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
