// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSSHxqU1xeZV_tTWzfi1HpgU5oZTp6JE',
    appId: '1:97436806148:web:7c675e51b72fca78511951',
    messagingSenderId: '97436806148',
    projectId: 'roomfinder-cec5a',
    authDomain: 'roomfinder-cec5a.firebaseapp.com',
    storageBucket: 'roomfinder-cec5a.firebasestorage.app',
    measurementId: 'G-BCET6G9GE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVyjv3z0_DWSnAp3iIhuBDFRE_LRVr920',
    appId: '1:97436806148:android:6ccf566b4b163f0e511951',
    messagingSenderId: '97436806148',
    projectId: 'roomfinder-cec5a',
    storageBucket: 'roomfinder-cec5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2iHh_BY9v_geHxTUMlQQtgqjZBxZaQk',
    appId: '1:97436806148:ios:d537d283534e67ef511951',
    messagingSenderId: '97436806148',
    projectId: 'roomfinder-cec5a',
    storageBucket: 'roomfinder-cec5a.firebasestorage.app',
    iosBundleId: 'com.example.roomFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDx2iHh_BY9v_geHxTUMlQQtgqjZBxZaQk',
    appId: '1:97436806148:ios:d537d283534e67ef511951',
    messagingSenderId: '97436806148',
    projectId: 'roomfinder-cec5a',
    storageBucket: 'roomfinder-cec5a.firebasestorage.app',
    iosBundleId: 'com.example.roomFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuSSHxqU1xeZV_tTWzfi1HpgU5oZTp6JE',
    appId: '1:97436806148:web:918149ae11703618511951',
    messagingSenderId: '97436806148',
    projectId: 'roomfinder-cec5a',
    authDomain: 'roomfinder-cec5a.firebaseapp.com',
    storageBucket: 'roomfinder-cec5a.firebasestorage.app',
    measurementId: 'G-EWYP81LL21',
  );
}
