name: room_finder
description: "Room Finder"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:      ^3.13.0  
  cloud_firestore:    ^5.6.6     
  firebase_auth:      ^5.5.2      
  firebase_storage:   ^12.4.5    
  image_picker:       ^1.0.8
  fluentui_system_icons: ^1.1.227
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  intl: ^0.19.0  
  phosphor_flutter: ^2.1.0
  flutter_chat_ui: ^1.6.6  
  flutter_firebase_chat_core: ^1.6.8
  flutter_chat_types: ^3.5.1
  flutter_typeahead: ^5.1.0
  http: ^1.2.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  adaptive_icon_background: "#5B63F2"

flutter_native_splash:
  color: "#656BFA"
  image: assets/logo.png
  color_dark: "#656BFA"
  image_dark: assets/logo.png
  android_12:
    image: assets/logo.png
    icon_background_color: "#656BFA"
    icon_background_color_dark: "#656BFA"

