name: room_finder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluentui_system_icons: ^1.1.227
  firebase_core: ^3.13.0
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


