name: room_finder
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core:      ^3.13.0  
  cloud_firestore:    ^5.6.6     
  firebase_auth:      ^5.5.2      
  firebase_storage:   ^12.4.5    
  image_picker:       ^1.0.8
  fluentui_system_icons: ^1.1.227
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


